version: "3.9"
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:delegated
      - ./tmp/shared:/tmp/shared:cached
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=commitchange_development_legacy
  memcached:
    image: memcached:alpine3.21
    ports:
      - "11211:11211"
    restart: always
  chrome:
    # See https://github.com/browserless/chrome/issues/1393
    image: browserless/chrome:latest
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      CHROME_URL: http://chrome:3333
      # Set connection timeout for debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000
  web:
    build: .
    volumes:
      - ${HOME}${USERPROFILE}/.netrc:/home/app/.netrc # for heroku credentials
      - ./app:/app/app
      - ./bin:/app/bin
      - ./client:/app/client
      - ./config:/app/config
      - ./db:/app/db
      - ./houdini:/app/houdini
      - ./javascripts:/app/javascripts
      - ./lib:/app/lib
      - ./log:/app/log
      - ./public:/app/public
      - ./script:/app/script
      - ./spec:/app/spec
      - ./types:/app/types
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - BUILD_DATABASE_URL=postgres://admin:password@db/commitchange_development_legacy
    depends_on:
      - db
      - memcached
    env_file: ".env"
