mailer:
  delivery_method: "smtp"
  address: "localhost"
  port: 1025

cdn:
  url: "http://localhost:5000"
  port: 5000

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket: commitchange-test-bucket