mailer:
  host: "https://us.commitchange.com"

mailer:
  delivery_method: "aws"
  host: "us.commitchange.com"

cdn:
  url: "https://assets.us.commitchange.com"

api_domain:
  url: 'https://us.commitchange.com'

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket_name: commitchange

button_config:
  url: "https://us.commitchange.com"