mailer:
  host: "https://us.commitchange.com"

mailer:
  delivery_method: "aws_ses"
  host: "commitchange.com"

cdn:
  url: "https://d2e5we1j08b82a.cloudfront.net"

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket: commitchange

button_config:
  url: "https://us.commitchange.com"