
name: Main build
on: 
  pull_request:
    types: [opened, reopened, synchronize]
concurrency: 
  group: build--${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04]
          node: [14.19.1]
          ruby: ['2.6.10']
        fail-fast: false
      steps:
        - uses: actions/checkout@v2
        - uses: dorny/paths-filter@v2
          id: changes
          with:
            filters: |
              ruby:
                - 'app/**'
                - 'bin/**'
                - 'config/**'
                - 'db/**'
                - 'gems/**'
                - 'lib/**'
                - 'public/**'
                - 'script/**'
                - 'spec/**'
                - '.ruby-version'
                - '.rspec'
                - 'config.ru'
                - 'Gemfile'
                - 'Gemfile.lock'
                - 'Rakefile'
              js:
                - '**/*.js*'
                - '**/*.es6'
                - '**/*.ts*'
                - '**/*.json'
                - package.json
                - yarn.lock
                - '.nvmrc'
                - '.babelrc'
                - '.bootstraprc'
                - '.browserlistrc'
                - '.jshintrc'
              
        - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
          uses: Daniel-Marynicz/postgresql-action@0.1.0
          with:
            postgres_image_tag: 12-alpine
            postgres_user: admin
            postgres_password: password
        - uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
            cache: 'yarn'
        - name: set environment variables
          uses: allenevans/set-env@v2.0.0
          with:
            CUSTOM_RUBY_VERSION: ${{ matrix.ruby }}
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
            bundler-cache: true
      
        - run: bin/setup
        - if: steps.changes.outputs.ruby == 'true'
          name: run spec
          run: bin/rake spec
        - if: steps.changes.outputs.ruby == 'true'
          run: script/compile-assets.sh
        - if: steps.changes.outputs.js == 'true'
          run: yarn build
        - if: steps.changes.outputs.js == 'true'
          run: yarn jest
