
# License: LGPL-3.0-or-later
name: Javascript build and test
env: 
  ruby: '2.4.10'
on: 
  pull_request:
    paths-ignore:
      - "**.md"
    types: [opened, reopened, synchronize]
jobs:
  package-download: # this downloads and caches all of the packages. That way if a future job fails, the caching will still occur
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.6.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - run: npm ci
  compile:
    needs: package-download
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.6.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
        uses: Daniel-Marynicz/postgresql-action@0.1.0
        with:
          postgres_image_tag: 11-alpine
          postgres_user: admin
          postgres_password: password
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - run: bin/setup
      - name: run build-all
        run: npm run ci-build-all
  jest:
    needs: package-download
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.6.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
        uses: Daniel-Marynicz/postgresql-action@0.1.0
        with:
          postgres_image_tag: 11-alpine
          postgres_user: admin
          postgres_password: password
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - run: bin/setup
      - run : npm run generate-api-js
      - name: run jest
        run: npx jest